
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 3.02
//   File : person_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Bond.PerformanceTest.Bond
{
    using System.Collections.Generic;

    
    [System.CodeDom.Compiler.GeneratedCode("gbc", "3.02")]
    public enum Gender
    {
        Male,
        Female,
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "3.02")]
    public partial class Passport
    {
        [global::Bond.Id(0)]
        public string number { get; set; }

        [global::Bond.Id(1)]
        public string authority { get; set; }
        
        public Passport()
            : this("Bond.PerformanceTest.Bond.Passport", "Passport")
        {}

        protected Passport(string fullName, string name)
        {
            number = string.Empty;
            authority = string.Empty;
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "3.02")]
    public partial class PoliceRecord
    {
        [global::Bond.Id(0)]
        public int id { get; set; }

        [global::Bond.Id(1)]
        public string crime { get; set; }
        
        public PoliceRecord()
            : this("Bond.PerformanceTest.Bond.PoliceRecord", "PoliceRecord")
        {}

        protected PoliceRecord(string fullName, string name)
        {
            crime = string.Empty;
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "3.02")]
    public partial class Person
    {
        [global::Bond.Id(0)]
        public string firstName { get; set; }

        [global::Bond.Id(1)]
        public string lastName { get; set; }

        [global::Bond.Id(3)]
        public uint age { get; set; }

        [global::Bond.Id(4)]
        public Gender gender { get; set; }

        [global::Bond.Id(5), global::Bond.Type(typeof(global::Bond.Tag.nullable<Passport>))]
        public Passport passport { get; set; }

        [global::Bond.Id(6)]
        public List<PoliceRecord> policeRecords { get; set; }
        
        public Person()
            : this("Bond.PerformanceTest.Bond.Person", "Person")
        {}

        protected Person(string fullName, string name)
        {
            firstName = string.Empty;
            lastName = string.Empty;
            gender = new Gender();
            policeRecords = new List<PoliceRecord>();
        }
    }
} // Bond.PerformanceTest.Bond
