//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: person.proto
namespace ProtobufNet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Passport")]
  public partial class Passport : global::ProtoBuf.IExtensible
  {
    public Passport() {}
    
    private string _number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string number
    {
      get { return _number; }
      set { _number = value; }
    }
    private string _authority;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"authority", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string authority
    {
      get { return _authority; }
      set { _authority = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PoliceRecord")]
  public partial class PoliceRecord : global::ProtoBuf.IExtensible
  {
    public PoliceRecord() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _crime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"crime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string crime
    {
      get { return _crime; }
      set { _crime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Person")]
  public partial class Person : global::ProtoBuf.IExtensible
  {
    public Person() {}
    
    private string _firstName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"firstName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string firstName
    {
      get { return _firstName; }
      set { _firstName = value; }
    }
    private string _lastName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"lastName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lastName
    {
      get { return _lastName; }
      set { _lastName = value; }
    }
    private int _age;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int age
    {
      get { return _age; }
      set { _age = value; }
    }
    private Gender _gender;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Gender gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private Passport _passport = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"passport", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Passport passport
    {
      get { return _passport; }
      set { _passport = value; }
    }
    private readonly global::System.Collections.Generic.List<PoliceRecord> _police_records = new global::System.Collections.Generic.List<PoliceRecord>();
    [global::ProtoBuf.ProtoMember(6, Name=@"police_records", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PoliceRecord> police_records
    {
      get { return _police_records; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Node")]
  public partial class Node : global::ProtoBuf.IExtensible
  {
    public Node() {}
    
    private int _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int data
    {
      get { return _data; }
      set { _data = value; }
    }
    private Node _left = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"left", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Node left
    {
      get { return _left; }
      set { _left = value; }
    }
    private Node _right = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"right", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Node right
    {
      get { return _right; }
      set { _right = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Gender")]
    public enum Gender
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Male", Value=0)]
      Male = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Female", Value=1)]
      Female = 1
    }
  
}